title: itunes
targets:
  - title: those_dancing_days
    url: https://itunes.apple.com/search?term=those+dancing+days&country=gb&media=music&entity=album
    pipelining: 5
    duration: 5
  - title: arab_strap
    url: https://itunes.apple.com/search?term=arab+strap&country=gb&media=music&entity=album
    connections: 20
    pipelining: 10
    duration: 5
output:
  local:
    errors: true
    latency: true
    requests: true
    throughput: true
    timeouts: true
    outputPath: /Users/donald/JavaScript/winchester/examples/output
  statsD:
    host: http://localhost/statsd
    port: 8125
    prefix: itunes.api
